In [1]:
import gym
import numpy as np
import gym_map_bro
import toy_agents
import pandas

env = gym.make('map-bro-v0')

In [2]:
env.__myinit__()

In [3]:
# New batch of 5 lines, here represented by 5 random values
np.random.seed(0)
new_batch = np.random.uniform([10.0, 10.0, 10.0, 10.0, 10.0])
print(new_batch)
batch = pandas.read_csv("dns.log", header=1)

[5.06067846 3.5632957  4.57512962 5.09605135 6.18710681]


In [4]:
# Run the Q agent
lr = .9
y = .95
num_episodes = 100
Q, rList = toy_agents.delayed_reward_agent(env, new_batch, lr, y, num_episodes)
print(Q)

[[ 0.45180005 -4.85718514]
 [ 0.05124368 -1.64849026]
 [ 1.04489175 -2.77144844]
 [ 1.53060843 -3.92820543]
 [ 1.10612078 -6.18710681]
 [ 0.          0.        ]]


In [5]:
# Determine best actions for the batch
batch_actions = np.argmax(Q, axis=1)
print(batch_actions[0:5])

# Perform the recommended actions
env.time_step(batch, new_batch, batch_actions[0:5])
print(env.values0_init)
print(env.df0)

[0 0 0 0 0]
[[0.         5.06067846]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]] 5.060678464654077
[[0.         3.5632957 ]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]] 3.563295702648225
[[0.         4.57512962]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]] 4.5751296153552055
[[0.         5.09605135]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0.         6.18710681]
 [0. 